### ISSUE TITLE
When I am editing a sentence I loose folder information

### ISSUE THREAD

**Issue by emanuelerangan** [linediconsine/tabae#3]
# Steps to reproduce
From logged dashboard, select a folder and then a sentence inside that folder, then click "edit".

# Actual result
The sentence does not show folder information

# Expected result
The sentence should show the correct folder information ( since it is in a folder )

**Comment by linediconsine** [comment]
Hi Emanuele,
I can reproduce this issue.
I will check what's going on soon

Thanks

**Comment by linediconsine** [comment]
This should be fixed on the codebase here.

I will also update[tabae.cloud](https://tabae.cloud) asap

Again thanks for reporting this bug

Marco

**Comment by linediconsine** [comment]
Closing this issue
