### ISSUE TITLE
Icons order

### ISSUE THREAD

**Issue by SebastienVermandel** [linediconsine/tabae#4]
When you create a new sentence, it appears before the ones that were already existing... It would be nice : 1- to sort the icons by chronological order (the oldest first...), 2- to allow the user to rearrange the order.

**Comment by linediconsine** [comment]
Hi Sebastien,
About 1
The easy thing to do could an ordering icon ( older first, newer first ) 
Some users prefer last one created on top and vice versa.

Something like : 
![Screenshot 2021-06-21 at 20 41 14](https://user-images.githubusercontent.com/1525362/122812294-cc266c00-d2d1-11eb-900a-a2ab07d0ed30.png)

about 2
_to allow the user to rearrange the order._  
We need an usable and clever way to to this without add complexity to the UX of the dashboard

**Comment by linediconsine** [comment]
@SebastienVermandel Hi, Please check this update on tabae.cloud and in this repo ( PR https://github.com/linediconsine/tabae/pull/7 )

![Screenshot 2021-07-17 at 22 37 00](https://user-images.githubusercontent.com/1525362/126048843-3eb97227-2e38-4e30-b33a-999a05fa4d4a.png)

**Comment by linediconsine** [comment]
About the suggestion 

 2- to allow the user to rearrange the order.

I am planning a rewrite of how the sentences are showed ( that could make the develop of this feature easier )

Thanks and please let me know any feedback on this feature

**Comment by linediconsine** [comment]
@SebastienVermandel 
I will close this issue, please let me know if any improvements/suggestions comes up

Thanks
